CREATE DATABASE `gb_yii2`;
CREATE TABLE `tweets` ( `id` INT UNSIGNED NOT NULL , `text` VARCHAR(512) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

